import Head from "next/head";
import Link from "next/link";
import Button from "../components/Button";

import tw from "twin.macro";

export default function Home() {
  return (
    <div tw="relative">
      <Head>
        <title>Spotify Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="py-15p bg-black w-full text-white"
        style={{ height: "100vh" }}
      >
        <h1>Spotify Profile</h1>

        <Button className="absolute">SK77</Button>
      </main>

      <footer tw="bg-black w-full text-white text-center p-2 grid place-items-center fixed bottom-0">
        <Link href="https://mahmoodkhan.me">
          <a target="_blank" rel="noopener noreferrer">
            ⚡<div className="inline -m-2 p-1">K77</div>
          </a>
        </Link>
      </footer>
    </div>
  );
}
